#!/bin/bash

function install_repositories() {

  sudo apt-get -y -q update
  sudo apt-get -y -q install curl

  curl -s https://packagecloud.io/install/repositories/whitewaterfoundry/wlinux-base/script.deb.sh | sudo bash
  curl -s https://packagecloud.io/install/repositories/whitewaterfoundry/wlinux-setup/script.deb.sh | sudo bash
  curl -s https://packagecloud.io/install/repositories/whitewaterfoundry/wslu/script.deb.sh | sudo bash

}

function install_packages() {

  sudo apt-get -y -q install wlinux-base wslu wlinux-setup

  #Remove packagecloud repository definitions
  sudo rm /etc/apt/sources.list.d/whitewaterfoundry_*.list

  #Update packagecloud repository definition for wslu
  curl -s https://packagecloud.io/install/repositories/whitewaterfoundry/wslu/script.deb.sh | sudo bash

  sudo apt-get -y -q update
}

function invoke_setup() {
  sudo ln -s /usr/local/bin/wlinux-setup /etc/setup
  /usr/local/bin/wlinux-setup

}


function main() {

  if [[ ! -f /usr/local/bin/wlinux-setup ]]; then
    install_repositories
    install_packages
  fi

  invoke_setup

}


main "$@"

exit 0